### PR TITLE
Added console width resize, and updated resize icon to reflect the feature

### PR DESCRIPTION
**Pull request by EricBatlle**
Added console width resize, and updated resize icon to reflect the feature.

I don't know if it's something that you want on your plugin, but it's something that I missed on your awesome plugin and maybe somebody else too ^^

### CODE REVIEW

**Comment by yasirkula** [comment]
I could pull this request with a few modifications. As the first revision, could you use tabs instead of spaces in the modified lines? And make sure that Windows line endings are used.

**Comment by EricBatlle** [comment]
> I could pull this request with a few modifications. As the first revision, could you use tabs instead of spaces in the modified lines? And make sure that Windows line endings are used.

I've used tabs instead of spaces on a Windows-Visual Studio so all should be nice...but If you say that I'll doble check it!

**Comment by EricBatlle** [comment]
@yasirkula You were completly right, I've normalized the entire file, it's correct now?

**Comment by yasirkula** [comment]
Now it says that all lines are modified 😄 I'd rather keep the diff restricted to only the modified lines.

**Comment by yasirkula** [comment]
That's what I feared: https://github.com/yasirkula/UnityIngameDebugConsole/blame/d5bda6bfb2c684ce5fd6d3421976a5905aede933/Plugins/IngameDebugConsole/Scripts/DebugLogManager.cs. I don't know if it is possible to revert Blame history to previous versions. I can't accept this PR like this, so I'll ask you to create a new PR. But beforehand, let me add some review notes to your current commit so that you could add them in the next PR. Will let you know when I'm finished.

**Comment by EricBatlle** [comment]
No problem, sorry for the inconvenience, I'll wait your notes.
In addition, if you can check if this [commit](https://github.com/yasirkula/UnityIngameDebugConsole/pull/52/commits/70753a1a5c8a3626ae53257beac15deb8d02ac9d) has the correct format, to be sure that the next PR won't be a mess like this one ^^'

**Comment by yasirkula** [comment]
Now it uses proper tabs, thanks. Can't tell if it uses Windows line endings but I'd like to believe that it is. It'd also be great if you could follow the same code style that I'm using (check where I put spaces in if conditions and function declarations) . Since this is a short PR, it should be relatively easy.

I've tested the code myself and noticed that it resizes the window from left to right. It is counter-intuitive since you'd expect it to resize from the resize button. Do you have any reasons for the current behaviour?

**Comment by EricBatlle** [comment]
> Now it uses proper tabs, thanks. Can't tell if it uses Windows line endings but I'd like to believe that it is. It'd also be great if you could follow the same code style that I'm using (check where I put spaces in if conditions and function declarations) . Since this is a short PR, it should be relatively easy.

Of course, I can follow those guidelines.

> I've tested the code myself and noticed that it resizes the window from left to right. It is counter-intuitive since you'd expect it to resize from the resize button. Do you have any reasons for the current behaviour?

Good point, and no, after thinking it...there is no logical reason to be like that, and as you said is counter-intuitive, I'll change that.

Something else?

**Comment by yasirkula** [comment]
I've added a couple of review notes. Will be waiting for your new PR 😺

**Pull request closed without merging**
